languageCode = "en-us"
pygmentsStyle = "atom"
pygmentsUseClasses = true
enableRobotsTXT = true
theme = "ajonp-fireship-theme"
[outputs]
home = ["HTML", "RSS", "Algolia"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params]
mainSections = ["lessons", "snippets"]

[params.algolia]
vars = ["title", "description", "summary", "date", "publishdate", "lastmod", "permalink"]
params = ["tags"]
